version: "3.4"

services:
  web:
    image: ambientum/php:7.4-nginx
    container_name: take-care
    volumes:
      - .:/var/www/app:delegated
    ports:
      - 8008:8080
    depends_on:
      - db
    environment:
      - PHP_MEMORY_LIMIT=-1
      - COMPOSER_MEMORY_LIMIT=-1
  db:
    container_name: mysql_take-care
    image: mysql:5.7
    ports:
      - "5808:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: take_care
volumes:
  quickdev-data:
    driver: local
